name: CI Workflow  # El nombre de tu flujo de trabajo

on:
  push:
    branches:
      - main  # Se ejecuta cada vez que subas cambios a la rama "main"
  pull_request:
    branches:
      - main  # También cuando haces un "pull request" a la rama "main"

jobs:
  build:
    runs-on: ubuntu-latest  # El sistema operativo que usará para ejecutar los pasos

    steps:
    - name: Checkout code  # Paso para descargar tu código
      uses: actions/checkout@v3

    - name: Set up Node.js and Yarn  # Paso para configurar Node.js y Yarn
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Usar la versión de Node.js que necesitas

    - name: Install dependencies with Yarn  # Instalar las dependencias con Yarn
      run: yarn install --frozen-lockfile

    - name: Run tests  # Paso para ejecutar tus pruebas (si las tienes)
      run: yarn test

    - name: Build project  # Paso para construir el proyecto (si es necesario)
      run: yarn build
